on:
  push:

name: Integration tests
jobs:
  drive_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
          channel: 'stable'

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Start iOS Simulator
        uses: futureware-tech/simulator-action@v1
        with:
          model: "iPhone 13"
          erase_before_boot: true
          shutdown_after_job: true

      - name: Run flutter e2e tests
        run: flutter test integration_test/app_test.dart

  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [google_apis]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
          channel: 'stable'

      # Run integration test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: pixel_4a
          script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
          # script: flutter test integration_test/app_test.dart

      # - name: Archive failed e2e
      #   if: failure()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: e2e-fail-screenshots
      #     retention-days: 14
      #     if-no-files-found: ignore
      #     path: |
      #       **/failures/*.png